title: Mojang Maps
description: A Google Maps like navigation system for Minecraft.
theme: just-the-docs

url: https://mojangmaps.abelkrijgtalles.nl

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
